name: jumpstart

services:
  postgres:
    image: postgres:15.15-trixie
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Tig33se23
      POSTGRES_DB: testdb 
    ports: 
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

    
  # web:
  #   image: nginx:latest
  #   ports:
  #     - "8080:80"
volumes:
  postgres_data:
    driver: local